CREATE TABLE USUARIO (
  USU_ID INT(28) NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(200) NOT NULL,
  APELLIDO LONGTEXT NOT NULL,
  CORREO LONGTEXT NOT NULL,
  PASSWORD LONGTEXT NOT NULL,
  PRIMARY KEY (USU_ID)
);

CREATE TABLE ACTOR (
  ACT_ID INT(28) NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(125) NOT NULL,
  DESCRIPCION LONGTEXT,
  FOTO LONGTEXT,
  FECHA_NACIMIENTO VARCHAR(30),
  PRIMARY KEY (ACT_ID)
);


CREATE TABLE PELICULA (
  PEL_ID INT(28) NOT NULL AUTO_INCREMENT,
  NOMBRE LONGTEXT NOT NULL,
  DIRECTOR LONGTEXT NOT NULL,
  FECHA_ESTRENO VARCHAR(30) NOT NULL,
  RESUMEN LONGTEXT NOT NULL,
  TRAILER LONGTEXT NOT NULL,
  PRIMARY KEY (PEL_ID)
);

CREATE TABLE COMENTARIO (
  COM_ID INT(28) NOT NULL AUTO_INCREMENT,
  USUARIO_USU_ID INT(28) NOT NULL,
  PELICULA_PEL_ID INT(28),
  DESCRIPCION LONGTEXT,
  PRIMARY KEY (COM_ID),
  FOREIGN KEY (USUARIO_USU_ID) REFERENCES USUARIO (USU_ID),
  FOREIGN KEY (PELICULA_PEL_ID) REFERENCES PELICULA (PEL_ID)
);

CREATE TABLE REPARTO (
  REP_ID INT(28) NOT NULL AUTO_INCREMENT,
  PELICULA_PEL_ID INT(28) NOT NULL,
  ACTOR_ACT_ID INT(28) NOT NULL,
  PRIMARY KEY (REP_ID),
  FOREIGN KEY (PELICULA_PEL_ID) REFERENCES PELICULA (PEL_ID),
  FOREIGN KEY (ACTOR_ACT_ID) REFERENCES ACTOR (ACT_ID)
);

CREATE TABLE WATCHLIST (
  WAT_ID INT(28) NOT NULL AUTO_INCREMENT,
  USUARIO_USU_ID INT(28) NOT NULL,
  PELICULA_PEL_ID INT(28) NOT NULL,
  PRIMARY KEY (WAT_ID),
  FOREIGN KEY (USUARIO_USU_ID) REFERENCES USUARIO (USU_ID),
  FOREIGN KEY (PELICULA_PEL_ID) REFERENCES PELICULA (PEL_ID)
);

CREATE TABLE CALIFICACION (
  CAL_ID INT(28) NOT NULL AUTO_INCREMENT,
  USUARIO_USU_ID INT(28) NOT NULL,
  PELICULA_PEL_ID INT(28),
  PUNTEO INT NOT NULL,
  PRIMARY KEY (CAL_ID),
  FOREIGN KEY (USUARIO_USU_ID) REFERENCES USUARIO (USU_ID),
  FOREIGN KEY (PELICULA_PEL_ID) REFERENCES PELICULA (PEL_ID)
);
